site_name: Stonks
theme:
  name: material
site_description: Documentation for the Stonks project
site_url: https://mkovacevich18.github.io/stonks/
repo_url: https://github.com/mkovacevich18/stonks
repo_name: mkovacevich18/stonks

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Getting Started:
      - Quickstart: getting-started.md
  - Guides:
      - Data Preprocessing: guides/data_preprocessing.md
      - Feature Engineering: guides/feature_engineering.md
      - Plotting: guides/plotting.md
  - Research:
      - Votatility Forecasting: research/volatility_forecasting.md
