name: Deploy docs (hatch)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install hatch & deps
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build site (hatch)
        run: |
          hatch run docs:build

      - name: Deploy to stonks.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: your-username/stonks.github.io
          publish_dir: ./site
          publish_branch: main
